[general]
# This command tells Streamlit to run the shell script first, 
# then install Python dependencies.
install_command = "bash install_treetagger.sh && pip install -r requirements.txt"

[runner]
# Settings related to the Python runner process
magicEnabled = false

[server]
# Settings related to the web server
maxUploadSize = 200
